### ISSUE TITLE
File size is zero after calling Writer::finish

### ISSUE THREAD

**Issue by jforberg** [image-rs/image-png#329] opened 2022-02-06 20:26 UTC
The size of the encoder's output file is still zero after calling finish.

The documentation suggests that finish() should finish writing out the file.

I added a repro case to your test suite, here: https://github.com/jforberg/image-png/tree/finish-bug-repro

**Comment by fintelia** [comment] 2022-02-06 20:38
It looks like the issue is that `Writer::finish` doesn't call flush on the wrapped writer. Since you are using a BufWriter, that means that the bytes are not pushed out to disk until the object is dropped

**Comment by HeroicKatora** [comment] 2022-02-06 20:47
This is a bug in `png`. We _could_ just ensure to call `flush()` on the underlying writer, and indeed this would allow us to report the error from the flush if any, but the bug goes a bit deeper than that. https://github.com/image-rs/image-png/blob/master/src/encoder.rs#L959-L960

This was introduced to stop the _inherent_ drop from also writing a second IEND chunk. However, it has the side effect of alos not calling other `Drop` implementations of fields. It could leak memory if called with `Cursor<Vec<u8>>` or similar resource-owning writers.

**Comment by fintelia** [comment] 2022-02-06 21:13
Yeah, we should probably get rid of the ManuallyDrop stuff in favor of a iend_written field that gets checked in the drop impl _and_ also flush the inner writer in case it is something like a `&mut BufWriter` which IIRC won't actually flush itself upon being dropped

**Closed** 2022-02-06 23:54 UTC
