### ISSUE TITLE
Up, Avg, and Paeth filters producing incorrect results

### ISSUE THREAD

**Issue by okaneco** [image-rs/image-png#199] opened 2020-04-17 14:35 UTC
I was originally using `image` to write .png files but wanted to use Best/High compression and the None filter. I'm using very limited colors and the file sizes were massive but I had no way to adjust the settings. I added `png` to my project and was able to get the compression gains I wanted but the FilterTypes produce strange results, except for None/0 and Sub/1.

The original image, "blossom.png", has 8 colors and was made with ColorType::RGB, Compression::Best, and FilterType::NoFilter. In my project I'm opening a .jpg or .png with `image`, doing color operations with `palette`, and then I convert those colors back to a Vec\<u8\>. I've created a small example program which mimics my project and have run other files through it which produce similar results for the filters in question. `cargo run --release -- blossom.png` to run it (or any other .png in the crate directory), it encodes a file for each filter type.

`main.rs`
```rust
fn main() {
    let name = std::env::args().nth(1).unwrap();
    let img = image::open(&name).unwrap().to_rgb();
    let (imgx, imgy) = (img.dimensions().0, img.dimensions().1);
    let buffer = img.into_raw();

    for n in 0..5 {
        let title = format!("{}-{}.png", name, n);
        let file = std::fs::File::create(&title).unwrap();
        let w = std::io::BufWriter::new(file);
        let mut enc = png::Encoder::new(w, imgx, imgy);
        enc.set_color(png::ColorType::RGB);
        enc.set_filter(png::FilterType::from_u8(n as u8).unwrap());
        let mut writer = enc.write_header().unwrap();

        writer.write_image_data(&buffer).unwrap();
    }
}
```
Cargo.toml
```toml
[package]
name = "filters"
version = "0.1.0"
edition = "2018"

[dependencies.image]
version = "0.23"
default-features = false
features = ["png"]

[dependencies.png]
version = "0.16"
```
The original image. All the images are encoded with Best compression but it's not needed to reproduce the behavior.
![blossom](https://user-images.githubusercontent.com/47607823/79579235-54d5c680-8095-11ea-8683-615a6ae284d0.png)

NoFilter
![blossom png-0](https://user-images.githubusercontent.com/47607823/79579623-d299d200-8095-11ea-8cfb-3f493008a3a6.png)

Sub
![blossom png-1](https://user-images.githubusercontent.com/47607823/79579635-d594c280-8095-11ea-905d-494d90547a73.png)

Up
![blossom png-2](https://user-images.githubusercontent.com/47607823/79579464-9c5c5280-8095-11ea-9b44-bf67065c5c7f.png)

Avg
![blossom png-3](https://user-images.githubusercontent.com/47607823/79579468-9d8d7f80-8095-11ea-8f07-61a7e5baa74c.png)

Paeth
![blossom png-4](https://user-images.githubusercontent.com/47607823/79579474-9f574300-8095-11ea-99bc-15b506a447d8.png)

**Comment by HeroicKatora** [comment] 2020-04-17 15:23
Thanks for the bug report. The issue is that the encoder uses filtered values for the previous row whereas the specification requires it to use unfiltered values. This means that every row except the first is corrupted with prediction algorithms that use the previous row. Will be fixed in the next release.

**Closed** 2020-04-17 15:47 UTC
Labels: bug
