### ISSUE TITLE
Invalid PNG file generation

### ISSUE THREAD

**Issue by newpavlov** [image-rs/image-png#147] opened 2019-06-21 16:14 UTC
Compressing `1.pnm` in this [archive](https://github.com/image-rs/image-png/files/3315261/conv.tar.gz) using `png` crate results in an invalid PNG file. EyeOfGnome reports "bad adaptive filter value". Compression code can be found in the same archive. Changing just one pixel (uncomment line 16 in `main.rs`) results in a correct file being generated.

**Comment by aschampion** [comment] 2019-11-06 15:46
I ran into a similar issue and created a reproduction repo [here](https://github.com/aschampion/image-rs-png-bug-20191106) before finding this issue. Debug hits the same assertion as image-rs/deflate-rs#18. Would be nice to (in order of declining preference) switch to a fuzzed encoder (parallel to the decoder discussion in #151), fix the bug, and/or make the assertion in release mode since I only lucked into noticing the corrupted data in a production tool.

**Comment by newpavlov** [comment] 2019-11-08 01:11
This issue is still not fixed since `png` uses `deflate v0.7`.

**Comment by oyvindln** [comment] 2020-02-04 23:49
Dependency is updated in the git repo, but the versions on crates.io still depend on 0.7.

**Comment by Shnatsel** [comment] 2020-02-25 16:02
The fix has been in master for a while. Can we get a new point release on crates.io with the fix?

**Comment by HeroicKatora** [comment] 2020-02-25 16:22
It's going on the schedule for this weekend.

**Comment by HeroicKatora** [comment] 2020-03-02 01:26
`png` `0.16.0` has been published, and is going to be updated into `image`.

**Closed by HeroicKatora** 2020-03-02 01:26 UTC
