### ISSUE TITLE
Removing unnecessary copying in next_raw_interlaced_row

### ISSUE THREAD

**Issue by Ryan1729** [image-rs/image-png#61] opened 2017-07-21 23:35 UTC
I'm working on a game and I'm using this crate (through the [image](https://github.com/PistonDevelopers/image) crate,) to load two 1024 by 1024 textures on startup. In debug mode this takes around 1.4 seconds on my admittedly old/underpowered machine. (The game loads much faster in release mode.) So, I had a look at the source to see if there was any low-hanging fruit optimizations to be had. I found [this line](https://github.com/PistonDevelopers/image-png/blob/104b08036bf926d10fa96cec40b3134d337cccbf/src/decoder/mod.rs#L414-L415) where a new vector is being allocated and copies being made, just to effectively remove elements from the start of the vector. I haven't found a simple way to speed that up but I thought I would share what I have found.

I looked for a way to optimize the operation and found [this stackoverflow page](https://stackoverflow.com/questions/43026118/what-is-the-idiomatic-way-to-remove-the-first-n-elements-in-a-mutable-vec). It suggests either replacing the line with something like `self.current.drain(..rowlen);`, replacing the `Vec` with a `VecDeque` or using a custom data structure.

I tried `self.current.drain(..rowlen);` and didn't get measurably different results (it's still copying the elements). I also tried swapping out the `Vec` with a `VecDeque` but that seems to be non-trivial. There is an implementation of the custom datastructure [here](https://github.com/mikeyhew/rust-dvec) but the author themselves describes it as unfinished. The custom data structure more or less just keeps track of the offset into the front of the `Vec` so that might be the easier way to go.

**Comment by nwin** [comment] 2017-07-22 02:48
First of all it is not surprising that the code is slow in debug mode. Rust itself is slow without optimizations turned on. 

Secondly, are you sure that this is the root cause of it being slow? Seems to me that you're spending a lot of time optimizing something which gives only little gain. That allocation is only done once per row. The main factor will probably the inflating part where not much can be gained.

**Comment by nox** [comment] 2018-02-19 13:09
The method mentioned in this issue definitely needs optimising. [This](https://github.com/PistonDevelopers/image-png/blob/3bd4f9c0a7a878f795a0bb93bb25cf1cd8d8ec07/src/decoder/mod.rs#L415) reallocates the entire data that remains to be decoded once per row, in a loop.

**Comment by Shnatsel** [comment] 2020-06-21 18:45
I believe this is fixed by #91

**Comment by HeroicKatora** [comment] 2020-06-21 18:51
Right. And the introduction of a `scan_start` variable to [delay moves to the front of the vector](https://github.com/image-rs/image-png/blob/master/src/decoder/mod.rs#L699) at some point this year. True, should be fixed.

**Closed by HeroicKatora** 2020-06-21 18:51 UTC
